/*
Author: Mohammadreza Iman
Project Name: THESEUS
A master degree thesis project
Federal University of Rio de Janeiro (UFRJ), PPGI, Brazil
mohammadreza.iman@hotmail.com
*/
COMPONENT=THESEUS_SinkManagerAppC

include $(MAKERULES)

